export const FETCH_CALENDAR_DATA = 'FETCH_CALENDAR_DATA'
export const FETCH_CONTACTS_DATA = 'FETCH_CONTACTS_DATA'
export const FETCH_DROPBOX_DATA = 'FETCH_DROPBOX_DATA'
export const FETCH_SLACK_DATA = 'FETCH_SLACK_DATA'
export const FETCH_TWEET_DATA = 'FETCH_TWEET_DATA'
export const LOADING = 'LOADING';
export const SEARCH_TERM = 'SEARCH_TERM'